spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: userName
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  data:
    rest:
      base-path: /api
server:
  port: 8181